### ISSUE TITLE
Does not work with create-react-app

### ISSUE THREAD

**Issue by mpinter** [vacuumlabs/data-provider#17]
Seems like babel config is not compatible with the one used in create-react-app (tried on an 'empty' application) - this is unfortunate since create-react-app does not seem to allow babel config without ejecting.

![regenerator](https://user-images.githubusercontent.com/2327312/39622060-29052578-4f91-11e8-9968-352b0a8ed750.png)

@tomaskulich @radoh is this something easily fixable ?

**Comment by Siegrift** [comment]
@mpinter https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime
Just ```import "regenerator-runtime/runtime";``` as first line in index.js
