### ISSUE TITLE
Examples sometimes not working

### ISSUE THREAD

**Issue by Siegrift** [vacuumlabs/data-provider#21]
Strange scenario and I don't know if it happens only on my laptop. I can't run the examples when following these steps:
1) git clone & cd data-provider/example
2) yarn (install) & yarn start
3) recieve this error:
![data-prov](https://user-images.githubusercontent.com/22679154/40520901-f3e0652c-5fc8-11e8-81cf-4ffa6f5beb40.png)
4) when I try ```cd .. & yarn``` and try launching examples again I am stuck with the error.

When I first run ```yarn``` in **data-provider** folder and only then in **examples**, everything works...
@radoh

**Comment by SanjiKir** [comment]
Your build scripts are not compatible with Windows OS. I can't even run yarn on the data-provider package. Therefore I am running into the same problem as mentioned above.

**Comment by tomaskulich** [comment]
Fixed by https://github.com/vacuumlabs/data-provider/pull/26 . Not sure about the windows though.
