### ISSUE TITLE
Changing getData for existing data provider is not currently supported

### ISSUE THREAD

**Issue by Siegrift** [vacuumlabs/data-provider#22]
I have a map component which needs to fetch data according to the area represented by the map (this means the URL changes after every movement, zoom...). 

Are there any ideas/plans when this will be supported? Can I help?
@radoh @tomaskulich

**Comment by mpinter** [comment]
I don't think you're using this correctly - the idea, as far as I can tell, is that a data-provider with given ref should always return the same data (unless they change on the server ) / talk to the same endpoint. (Please correct me if I'm wrong).

If you really want to use data-providers for this, simply add the parameter you're changing to the ref. Or you might take another approach.

**Comment by Siegrift** [comment]
I think you are correct, I understood the provider a little different. After I put the params into ref everything works...
