### ISSUE TITLE
Mistake in README

### ISSUE THREAD

**Issue by NikitaKurpas** [vacuumlabs/data-provider#25]
This line in the README looks invalid: 
```
onData: (ref, data, dispatch) => updateBlogPost(props.blogPostId),
```
because of how `updateBlogPost` is defined:
```
const updateBlogPost = (blogPostId) => (ref, data, dispatch) => {
  dispatch({
    type: 'on-blog-post-data',
    payload: {blogPostId, data},
    description: `DataProvider ref=${ref}`,
  })
}
```

I think
```
onData: updateBlogPost(props.blogPostId),
```
is valid in this situation

I can do a PR if you want.

**Comment by mpinter** [comment]
Thanks a lot for catching this (also, awesome for doing so this fast :+1: ). We've had some changes which allowed using different syntax just a couple days ago, and missed this part.

No need for PR, should be fixed now.
